#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
figs an IP address received as an argument 5 times.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fings an IP address received as an argument 5 times.

if [ $# ii-eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fian inherited class-checking function."""
